project:
  type: website

website:
  title: "Dagmar Heintze"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Research
        menu: 
          - href: working papers.qmd
            text: Working Papers
          - href: peer-reviewd research.qmd
            text: Peer-reviewed Research
      - href: presentations.qmd 
        text: Conference Presentations 
      - href: CV 01_2024.pdf
        text: CV 
      - text: Assignments 
        menu: 
          - href: assignment1.qmd 
            text: Assignment1 
          - href: assignment2.qmd
            text: Assignment2.0 
          - href: Lab01.qmd
            text: Assignment2.1
          - href: Lab02.qmd
            text: Assignment2.2
          - href: assignment3.qmd 
            text: Assignment3

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

