project:
  type: website

website:
  title: Dagmar Heintze
  navbar:
    right:
      - href: index.html
        text: Home
      - text: Research
        menu: 
        - href: workingpapers.html
          text: Working Papers
        - href: research.html
          text: Peer-reviewed Research
      - text: Conference Presentations
        menu: 
        - href: 2023APSA_presentation_DHeintze.pdf
          text: APSA2023
        - href: 2024MPSA_presentation_DHeintze.pdf
          text: MPSA2024
      - href: CV 03_2024.pdf
        text: CV 
      
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

